### ISSUE TITLE
Add support to Gnome 41

### ISSUE THREAD

**Issue by pacho2** [pratap-panabaka/control-blur-effect-on-lockscreen#1]
It seems it doesn't support gnome 41 yet

Thanks a lot!

**Comment by pratap-panabaka** [comment]
Hi, Thanks for pinging me, I have updated in gnome-extensions website. Lets see if any issues araise.

**Comment by pacho2** [comment]
For now it seems to work nice

**Comment by pacho2** [comment]
Can you commit it to github repo too please

Thanks a lot

**Comment by pratap-panabaka** [comment]
yes, it is done.

Thank You!!!
