### ISSUE TITLE
Add support for GNOME 42

### ISSUE THREAD

**Issue by DmitriSSS** [pratap-panabaka/control-blur-effect-on-lockscreen#2]
After update to GNOME 42.beta Gnome extension doesn't work (outdated).
Please add support to the new version. Thank you in advance!

**Comment by pratap-panabaka** [comment]
@DmitriSSS, Hi.
I have updated the repo and also uploaded the extension for gnome-shell version 42 in gnome-extensions website.
please revert back once you check the extension with gnome-shell 42.

**Comment by DmitriSSS** [comment]
Everything works fine, thank you very much for your quick and high quality support!
