### ISSUE TITLE
Recent changes on default gnome-shell theme make password entry box to be hardly readable

### ISSUE THREAD

**Issue by pacho2** [pratap-panabaka/control-blur-effect-on-lockscreen#3]
With latest gnome-shell default theme updates (I think they were introduced in Gnome 41 cycle), the password entry box was made transparent, that makes the box hardly readable when using the extension with brilliant wallpapers. 

Maybe the entry box theme could be tweaked back to safer transparency/color options :/

Thanks a lot

**Comment by pacho2** [comment]
Maybe blur could be kept for the prompt screen. It seems it is the way gnome-shell-extension-unlockDialogBackground is handling this problem :thinking: 
https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground/blob/master/unlockDialogBackground%40sun.wxg%40gmail.com/extension.js#L74

**Comment by pratap-panabaka** [comment]
@pacho2 I will look into it in a couple of days. Thanks

**Comment by pratap-panabaka** [comment]
Hi, @pacho2 in v21 of this extension which is for gnome-shell v44. I have set the colour black for the password entry field. you can change it to any suitable colour by editing the extensions `stylesheet.css` file.

When you decide to keep the default colour set by GNOME, just delete this `stylesheet.css` file.

![password-entry-black](https://user-images.githubusercontent.com/40719899/230711399-20e3f82e-9d2c-4981-94b0-469c929021de.png)

![instruction](https://user-images.githubusercontent.com/40719899/230711620-b4b1322e-c6b7-43a0-9fc4-7e5ad8f9401b.png)

Thanks

**Comment by pacho2** [comment]
It works fine

Thanks a lot!
