### ISSUE TITLE
Add support for GNOME 43

### ISSUE THREAD

**Issue by pacho2** [pratap-panabaka/control-blur-effect-on-lockscreen#4]
It is not currently listed in the metadata

Thanks!

**Comment by Gunni** [comment]
Fixed in https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen/commit/85c403151ad02dd113007a81b78a32c23675c31d

**Comment by normanr** [comment]
Still needs to be updated on extensions.gnome.org

**Comment by pratap-panabaka** [comment]
Hi @normanr will do it in couple of days. Thank You

**Comment by pratap-panabaka** [comment]
Hi, @normanr can you test it now, please..
![image](https://user-images.githubusercontent.com/40719899/218761640-401d1f9e-a372-41e8-9aaf-b7b933a28b95.png)

**Comment by ciphernaut-rh** [comment]
Works for me, thank you.
Fedora 37, x86_64

**Comment by pratap-panabaka** [comment]
Thank you @ciphernaut-rh
