### ISSUE TITLE
Little issue after suspend

### ISSUE THREAD

**Issue by egayghost** [pratap-panabaka/control-blur-effect-on-lockscreen#7]
It seems like it doesn't work after some time of sleep, the blur is just gone at that point, not sure if it's meant to be like that or it's a bug.

**Comment by pratap-panabaka** [comment]
Hi, you mean, once your system is suspended and for some time you use your system and then lock, then there is no effect?
what is your gnome-shell version.

**Comment by pratap-panabaka** [comment]
@egayghost I just tried it in my ArchLinux with gnome-shell v45, the extension worked as expected.

**Comment by egayghost** [comment]
> Hi, you mean, once your system is suspended and for some time you use your system and then lock, then there is no effect? what is your gnome-shell version.

I'm on gnome v45 as well, just after closing the lid and wanted to use the system again, the blur is just gone. I'm not sure if it will conflict with blur my shell, there's an option there for lockscreen as well but I did disable and used this one.

**Comment by egayghost** [comment]
or maybe blur my shell is not completely ignoring it.

update: did remove blur my shell, same issue on my end

**Comment by pratap-panabaka** [comment]
Ok thats a nice catch, have you tried to disable blur-myshell extension and see whats the result? Better to disable blur-myshell extension and then logout and see.

**Comment by egayghost** [comment]
> Ok thats a nice catch, have you tried to disable blur-myshell extension and see whats the result? Better to disable blur-myshell extension and then logout and see.

just did it right now, still ended up the same result

**Comment by pratap-panabaka** [comment]
may I know your OS distribution name?

**Comment by egayghost** [comment]
> may I know your OS distribution name?

we're on the same actually xD, archlinux with gnome v45. Tbh the case of blur my shell is bit different as well, their lockscreen blur stops as well after closing lid and will use default's gnome blur. I guess it's a gnome issue.

**Comment by Neo-29** [comment]
I can confirm this issue>
The extension is off after suspend

**Comment by gary-host-laptop** [comment]
Same here, Fedora with Gnome 45.

**Comment by pratap-panabaka** [comment]
@egayghost I will look into this in a week time.

**Comment by Neo-29** [comment]
Now the extension goes OFF as soon as the extension manger is closed

**Comment by Neo-29** [comment]
What about this issue.
Something new about it?

**Comment by pratap-panabaka** [comment]
Hi @Neo-29 I have tested this in my Arch Linux with gnome-shell v45. I did not face this issue.
is the issue after suspend or after an extended sleep? I may have to change the OS to test it.
Please provide your OS and gnome-shell version.

Thanks.

**Comment by pratap-panabaka** [comment]
> Now the extension goes OFF as soon as the extension manger is closed

This is the expected behavior, the extension will work only on lock screen. The extension is configured to work when it detects lock screen.

**Comment by Neo-29** [comment]
I'm on arch gnome 45.3

The issue happens after a long time suspend ( hours)

**Comment by gary-host-laptop** [comment]
I'm on Fedora 39 Gnome 45.

**Comment by mario-estrada80** [comment]
> > Now the extension goes OFF as soon as the extension manger is closed
> 
> This is the expected behavior, the extension will work only on lock screen. The extension is configured to work when it detects lock screen.

that does not sound logical what if I want to suspend momentary the extension I will need to uninstall it, lock screen blur is working but it is not when I close the lid of my laptop and then open it, it used to work but not anymore, manjaro gnome 45

**Comment by Neo-29** [comment]
@PRATAP-KUMAR you have to investigate.
Tks.

**Comment by schlagmichdoch** [comment]
Ubuntu 23.10 Gnome 45 here. The extension works great whenever the lock screen activates through a timeout or when I use CMD/META + L to lock the device actively. When I close the lid though which activates the suspend mode, the extension is not activated.

Does the extension check for the lock screen itself or rather the process of going into lock screen? If the latter is true, it might be missing the lock screen when it comes out of suspend.

This is a great libre extension, thanks for your work! Please tell if we can help somehow!

**Comment by pratap-panabaka** [comment]
> > > Now the extension goes OFF as soon as the extension manger is closed
> > 
> > 
> > This is the expected behavior, the extension will work only on lock screen. The extension is configured to work when it detects lock screen.
> 
> that does not sound logical what if I want to suspend momentary the extension I will need to uninstall it, lock screen blur is working but it is not when I close the lid of my laptop and then open it, it used to work but not anymore, manjaro gnome 45

https://discourse.gnome.org/t/unlockdialog-unlockdialogclock-prototype-is-undefined/16866/27

**Comment by pratap-panabaka** [comment]
> @PRATAP-KUMAR you have to investigate. Tks.

Hi, It is working even after suspend in my Arch Linux. I am sorry for not being able to test it for extended suspend as my laptop always on since last few months. It will take some days for me to put my laptop in suspend for extended hours. If I get chance I will do that.

Thanks

**Comment by Neo-29** [comment]
> > @PRATAP-KUMAR you have to investigate. Tks.
> 
> Hi, It is working even after suspend in my Arch Linux. I am sorry for not being able to test it for extended suspend as my laptop always on since last few months. It will take some days for me to put my laptop in suspend for extended hours. If I get chance I will do that.
> 
> Thanks

I don't know what you mean by "extended suspend"
.
If you leave the laptop with the default configuration of energy power preset, you'll see quickly that when you go back on it, the blur on the lockscreen is gone.
We are many to report the issue here, you seem to kind of ignore it.

**Comment by pratap-panabaka** [comment]
Hi,

> I'm on arch gnome 45.3
> 
> The issue happens after a long time suspend ( hours)

I tested this extension with 10 min after suspend, 30 min after suspend. The lock screen blur is persistent. Extended suspend, I mean to keep the laptop for around 6 hours and then see.

Thank You @Neo-29

**Comment by pratap-panabaka** [comment]
> > > @PRATAP-KUMAR you have to investigate. Tks.
> > 
> > 
> > Hi, It is working even after suspend in my Arch Linux. I am sorry for not being able to test it for extended suspend as my laptop always on since last few months. It will take some days for me to put my laptop in suspend for extended hours. If I get chance I will do that.
> > Thanks
> 
> I don't know what you mean by "extended suspend" . If you leave the laptop with the default configuration of energy power preset, you'll see quickly that when you go back on it, the blur on the lockscreen is gone. We are many to report the issue here, you seem to kind of ignore it.

Energy Power Preset? Am I missing it? Please check below
![image](https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen/assets/40719899/3499e79e-8391-4e40-bed5-cd192dd57cb3)

**Comment by Neo-29** [comment]
![IMG_20240216_113622](https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen/assets/90937180/580a660e-3778-4a0e-92bd-fb5892706c39)
Leave it a night...you'll see the result.

![image](https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen/assets/90937180/1a006020-0822-4200-8c2e-9f3663d762ab)


No blur

**Comment by pratap-panabaka** [comment]
@Neo-29 Hi, I tried all the ways to reproduce, like closing the laptop lid, clicking on suspend button, leaving the system for about 6 hours after suspend, `sudo systemctl suspend`. I cannot reproduce the issue.

Thanks

**Comment by schlagmichdoch** [comment]
When I use `sudo systemctl suspend` the lock screen is first shown to be blurred before the laptop goes into suspend. After waking up from suspend the lock screen is not blurred anymore though.

**Comment by schlagmichdoch** [comment]
I compared the bahavior of this extension to the behavior of the working extension [Bing Wallpaper](https://github.com/neffo/bing-wallpaper-gnome-extension).

Apparently, when coming from suspend extensions are always disabled. The session mode "unlock-dialog" is only available when using the lock screen from a user session so when locking the screen using SUPER+L or `loginctl lock-session` via cmd the default blur should be set instead of a blur of 0 which is the behavior with this extension.

I'm pretty sure, your `disable()` method is not implemented correctly. The `_updateBackgroundEffects` method should be reset to its default value when disabling the extension. As this not done properly, the method is not callable, and the following error message is thrown (found using journalctl):
```log
Feb 20 14:41:14 U23 gnome-shell[3627]: JS ERROR: TypeError: this._updateBackgroundEffects is not a function
                                       _updateBackgrounds@resource:///org/gnome/shell/ui/unlockDialog.js:685:14
                                       _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:613:14
                                       @resource:///org/gnome/shell/ui/init.js:21:20

```
When coming from suspend this leads to the weird current behavior.

This might also explain, why the Gnome extensions app shows this extension as being disabled after suspension.

@PRATAP-KUMAR Maybe take a look at the implementation of the blur effect here to see whether you can fix it:
https://github.com/neffo/bing-wallpaper-gnome-extension/blob/aed4d21cc0fb5703ff2cd1838d7dbb0e437e00ec/blur.js

**Comment by gary-host-laptop** [comment]
> @Neo-29 Hi, I tried all the ways to reproduce, like closing the laptop lid, clicking on suspend button, leaving the system for about 6 hours after suspend, `sudo systemctl suspend`. I cannot reproduce the issue.
> 
> Thanks

I think that running a VM to reproduce the error would be the best idea, installing Fedora, then the extension and then simply locking the account should be enough for you to reproduce the issue. There's not need for waiting since as soon as you get out of your account the blur effect is gone. Thank you for your hard work, nonetheless.

**Comment by KentBrockman** [comment]
Hello

I seem to be able to reproduce this issue consistently. 
To be clear, the extension with my settings (sigma=1), appears to work fine on lock screens. 
Resuming from suspend, the extension appears to apply **without** settings and seems to revert to the default settings (sigma=0)

Here are details on my setup. I am running Debian Trixie w/ Gnome 46 on Wayland
```
> dconf read /org/gnome/shell/extensions/control-blur-effect-on-lockscreen/sigma
1
> dconf read /org/gnome/shell/extensions/control-blur-effect-on-lockscreen/brightness
0.65000000000000002
> gnome-shell --version
GNOME Shell 46.4
> cat ~/.local/share/gnome-shell/extensions/ControlBlurEffectOnLockScreen@pratap.fastmail.fm/metadata.json 
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Control the Blur Effect On Lockscreen.",
  "donations": {
    "buymeacoffee": "pratappanabaka"
  },
  "name": "Control Blur Effect On Lockscreen",
  "session-modes": [
    "unlock-dialog"
  ],
  "settings-schema": "org.gnome.shell.extensions.control-blur-effect-on-lockscreen",
  "shell-version": [
    "45",
    "46",
    "47"
  ],
  "url": "https://github.com/PRATAP-KUMAR/control-blur-effect-on-lockscreen",
  "uuid": "ControlBlurEffectOnLockScreen@pratap.fastmail.fm",
  "version": 26
}
> cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
> apt list --installed | grep wayland

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

kwayland-integration/testing,now 5.27.11-1+b1 amd64 [installed,automatic]
kwayland5-data/testing,now 4:5.115.0-5 all [installed,automatic]
libkf5waylandclient5/testing,now 4:5.115.0-5 amd64 [installed,automatic]
libqt5waylandclient5/testing,now 5.15.13-3 amd64 [installed,automatic]
libqt5waylandcompositor5/testing,now 5.15.13-3 amd64 [installed,automatic]
libqt6waylandclient6/testing,now 6.6.2-2 amd64 [installed,automatic]
libqt6waylandcompositor6/testing,now 6.6.2-2 amd64 [installed,automatic]
libva-wayland2/testing,now 2.22.0-1 amd64 [installed,automatic]
libwayland-bin/testing,now 1.23.0-1 amd64 [installed,automatic]
libwayland-client0/testing,now 1.23.0-1 amd64 [installed,automatic]
libwayland-cursor0/testing,now 1.23.0-1 amd64 [installed,automatic]
libwayland-dev/testing,now 1.23.0-1 amd64 [installed,automatic]
libwayland-egl1/testing,now 1.23.0-1 amd64 [installed,automatic]
libwayland-server0/testing,now 1.23.0-1 amd64 [installed,automatic]
qt6-wayland/testing,now 6.6.2-2 amd64 [installed,automatic]
qtwayland5/testing,now 5.15.13-3 amd64 [installed,automatic]
wayland-protocols/testing,now 1.37-1 all [installed,automatic]
wayland-utils/testing,now 1.2.0-1 amd64 [installed]
xwayland/testing,now 2:24.1.2-1 amd64 [installed,automatic]
```

Please ping me if you'd like any additional information or if I can assist in testing.

**Comment by pratap-panabaka** [comment]
Hi @KentBrockman I tried to produce the issue on my MSI Laptop with Arch Linux - GNOME 47 and Ubuntu 24.10 - GNOME 47 and the extension is working fine after suspend.

I have another laptop of HP brand with Arch Linux GNOME 47. I will try in that too and get back to you in a day or 2.

Thanks

**Comment by pratap-panabaka** [comment]
Hi @KentBrockman I took a week time and refactored this extension completely. Hopefully the latest one should work even after suspend. Can you try this one https://github.com/PRATAP-KUMAR/lockscreen-extension. First uninstall existing extension and then install lockscreen extension.

Thanks

**Comment by schlagmichdoch** [comment]
@PRATAP-KUMAR I can confirm that your new extension does indeed work so much better on Ubuntu 24.04 and all changes are persistent after suspend. Thank you!

**Comment by pratap-panabaka** [comment]
Thank You for your response. Yup there were many issues raised on this extension and unfortunately I never come across that issue nor I could reproduce it with my available desktops or laptops with Ubuntu, Arch Linux and occasionally Debian. So I took a week time to refactor it and deployed with GNOME extensions.

Thank You once again for your response.

**Comment by KentBrockman** [comment]
Hi @PRATAP-KUMAR 

I've installed the latest extension. It seems to work consistently.
It appears the settings menu has disappeared, so I cannot adjust sigma. This isn't an issue in dark mode, however in light mode this is what my desktop looks like.
![image](https://github.com/user-attachments/assets/e2f27934-35fb-4146-8365-4b16077a2b69)

**Comment by schlagmichdoch** [comment]
I was confused too at first but found out that the settings menu is now on the lock screen itself in the upper left corner

**Comment by pratap-panabaka** [comment]
@KentBrockman as @schlagmichdoch said the settings are on the lockscreen itself. Do let me know are you able to control blur radius/sigma and blur brightness.

[lockscreen-extension](https://github.com/PRATAP-KUMAR/lockscreen-extension)

Thanks

**Comment by KentBrockman** [comment]
My mistake, I see the settings now on the lock screen. Seems to work perfectly now, even from suspend. All settings preserved. Thank you so much for the fantastic work and the fantastic extension Pratap!
