### ISSUE TITLE
Login Screen ?

### ISSUE THREAD

**Issue by NeuHix** [pratap-panabaka/control-blur-effect-on-lockscreen#8]
Can you do the same for the login screen ?

**Comment by pratap-panabaka** [comment]
Hi is your login screen also blurred? Or you want to make it blur?

**Comment by NeuHix** [comment]
I use [GDM Settings](https://github.com/gdm-settings/gdm-settings) to customize the login screen.
It lets me choose a different background. 
but there are no blur options yet. 
I wanted to make it look like : 
![image](https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen/assets/94163435/44bc4c07-9fcb-438d-9f31-4af78e2390b0)

**Comment by pratap-panabaka** [comment]
the above image doesn't have blur, so what ever image you choose is fine rite.

The documentation for gnome-extensions for GDM is bit difficult to understand for me. I have tried to configure extension for GDM but failed. So only way is to set a blurred image. I remember I have answered an ask ubuntu question on this and made a script for it. let me find out that post. by the way what is your OS?

**Comment by NeuHix** [comment]
```
             .',;::::;,'.                arctrus@fedora 
         .';:cccccccccccc:;,.            -------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora release 38 (Thirty Eight) x86_64 
    .:cccccccccccccccccccccccccc:.       Kernel: 6.4.12-200.fc38.x86_64 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Uptime: 33 mins 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Packages: 3558 (rpm), 13 (brew), 106 (flatpak) 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Shell: fish 3.6.1 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Resolution: 1920x1080 
:cccccccccccccc;MMM.;cccccccccccccccc:   DE: GNOME 44.4 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   WM: Mutter 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM Theme: Custom-Accent-Colors 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: adw-gtk3 [GTK2/3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: MoreWaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: BlackBox 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: AMD Athlon 3000G (4) @ 3.500GHz 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobil 
:cccccccccccccccccccccccccccc:'.         Memory: 2960MiB / 13880MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                         
                                                                 

```

**Comment by NeuHix** [comment]
I did set a blurred image.
But GDM Settings doesn't provide any option to make the top bar transparent.
So the top bar is just a solid colour. (not blurred like the background wallpaper)

**Comment by pratap-panabaka** [comment]
you mean you want to make top bar transparent, is it what you are looking for?

**Comment by pratap-panabaka** [comment]
can you share screenshot of your GDM screen please.

**Comment by NeuHix** [comment]
Yes. Just see my GDM screen. the top bar is a solid colour.

![20231122_115020](https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen/assets/94163435/2110ed76-b5ef-41f8-8c82-eebb302b45aa)

**Comment by pratap-panabaka** [comment]
Oh ok, I got it. Can you change the shell theme from GDM settings to any other. Then its easy for you to customize this simply with that theme. No need extensions or anything. Just css will do.

**Comment by NeuHix** [comment]
I've never used css files to customise things. GDM Settings is an app on flathub.
Not an extension.
I just wanna make the top bar transparent.

**Comment by pratap-panabaka** [comment]
Hi, your issue is not appropriate for this extension (this repo). you may ask question on any forum related to your os and requirement.

Thanks
